// This file is where we keep all the "wiring" for talking to our smart contracts
// from the React app. It pulls in the ABIs (which describe what functions each
// contract has) and the addresses we deployed to on Ganache, then gives us a
// function to create ethers.js contract instances we can call methods on.

import { ethers } from "ethers";

// Each of these JSON files was generated by Hardhat when we compiled the
// contracts. The 'abi' field inside is the bit ethers cares about - it tells
// ethers what functions exist, what arguments they take, etc.
import RegistryArtifact from "./Registry.json";
import JobArtifact from "./Job.json";
import ReputationArtifact from "./Reputation.json";

// deployment.json was written by our Hardhat deploy script and contains the
// addresses where each contract lives on the Ganache chain.
import deploymentInfo from "./deployment.json";

// Pull out the addresses into a constant so we can use them elsewhere if needed
export const CONTRACT_ADDRESSES = deploymentInfo.addresses;

// We're using chain ID 1337 to match Ganache. The React app will use this to
// check that MetaMask is on the right network before trying to do anything.
export const CHAIN_ID = deploymentInfo.chainId;

// This function takes either a signer (for transactions that change state) or
// a provider (for read-only calls) and gives us back three contract instances
// we can use throughout the app.
//
// A signer is basically "an account that can pay gas" - it's what we get from
// MetaMask once the user connects their wallet. A provider is just a read-only
// connection to the chain.
export function getContracts(signerOrProvider) {
  const registry = new ethers.Contract(
    CONTRACT_ADDRESSES.Registry,
    RegistryArtifact.abi,
    signerOrProvider
  );

  const job = new ethers.Contract(
    CONTRACT_ADDRESSES.Job,
    JobArtifact.abi,
    signerOrProvider
  );

  const reputation = new ethers.Contract(
    CONTRACT_ADDRESSES.Reputation,
    ReputationArtifact.abi,
    signerOrProvider
  );

  return {
    registry: registry,
    job: job,
    reputation: reputation,
  };
}

// The Registry contract uses an enum for roles. Solidity enums get returned as
// numbers (0, 1, 2, 3), so we need a way to translate them into something we
// can show in the UI. These constants need to match the order in Registry.sol
// exactly - if we change the order there, we have to change it here too.
//
// TODO: figure out if there's a way to auto-generate these from the ABI so we
// don't have to keep them in sync manually
export const ROLE_NONE = 0;
export const ROLE_FREELANCER = 1;
export const ROLE_CLIENT = 2;
export const ROLE_VERIFIER = 3;

// Helper for turning a role number back into a readable string for the UI
export function getRoleLabel(roleNumber) {
  if (roleNumber === ROLE_FREELANCER) {
    return "Freelancer";
  } else if (roleNumber === ROLE_CLIENT) {
    return "Client";
  } else if (roleNumber === ROLE_VERIFIER) {
    return "Verifier";
  } else {
    // Either ROLE_NONE or something unexpected - treat as not registered
    return "Not registered";
  }
}

// Same idea as roles but for the Job contract's Status enum
export const STATUS_NONE = 0;
export const STATUS_OPEN = 1;
export const STATUS_ACCEPTED = 2;
export const STATUS_COMPLETED = 3;
export const STATUS_CONFIRMED = 4;

export function getStatusLabel(statusNumber) {
  if (statusNumber === STATUS_OPEN) {
    return "Open";
  } else if (statusNumber === STATUS_ACCEPTED) {
    return "Accepted";
  } else if (statusNumber === STATUS_COMPLETED) {
    return "Completed";
  } else if (statusNumber === STATUS_CONFIRMED) {
    return "Confirmed";
  } else {
    return "Unknown";
  }
}