// ---------------------------------------------------------------------
// src/contracts/index.js
// ---------------------------------------------------------------------
// this is the "wiring" file that connects our React frontend to the three
// smart contracts. nothing in here actually talks to the chain itself -
// it just sets up the bits we need so other files can.
//
// three things live here:
//   1. importing the ABIs (the JSON files Hardhat spits out when it
//      compiles - they describe what functions a contract has)
//   2. importing the deployment info (the addresses where the contracts
//      live on Ganache - this gets refreshed every time we redeploy)
//   3. a getContracts() helper that gives the rest of the app ready-made
//      ethers.js contract instances, plus a few constants and label
//      helpers for stuff like role enums
//
// basically nothing in the React app talks to ethers directly - everyone
// imports from here. keeps the rest of the code tidier.
// ---------------------------------------------------------------------

import { ethers } from "ethers";

// each of these JSON files was generated by Hardhat when it compiled our
// contracts. they contain a bunch of stuff but the bit ethers actually
// cares about is the 'abi' field - that's what tells ethers what
// functions the contract has, what args they take, what they return.
import RegistryArtifact from "./Registry.json";
import JobArtifact from "./Job.json";
import ReputationArtifact from "./Reputation.json";

// deployment.json gets written by our Hardhat deploy script and contains
// the addresses of the three contracts on Ganache. if we redeploy, we have
// to copy this file across from hardhat-deploy/deployments/ each time -
// the script in package.json could probably do this automatically but
// we just do it by hand for now.
import deploymentInfo from "./deployment.json";

// pull out the addresses so other files can import them by name. probably
// overkill having this as a separate export but makes the contract code
// a bit more readable in places where we need just the address.
export const CONTRACT_ADDRESSES = deploymentInfo.addresses;

// chain ID 1337 is the standard Ganache chain ID. the wallet hook uses
// this to double-check MetaMask is on the right network before doing
// anything - we don't want someone accidentally trying to send transactions
// on Ethereum mainnet thinking they're on our local chain.
export const CHAIN_ID = deploymentInfo.chainId;

// ---------------------------------------------------------------------
// getContracts
// ---------------------------------------------------------------------
// the workhorse of this file. you give it a signer (an account that can
// pay gas - basically what we get back from MetaMask after the user
// connects) or a provider (read-only connection to the chain), and it
// hands you back three ready-to-use ethers contract instances.
//
// the components in the rest of the app use this every time they need
// to do anything on-chain - it's how MyJobsView, BrowseJobsView etc.
// actually talk to the contracts.
// ---------------------------------------------------------------------
export function getContracts(signerOrProvider) {
  // for each contract, we make an ethers.Contract instance using:
  //   - the deployed address (from deployment.json)
  //   - the ABI (from the artifact json)
  //   - the signer or provider (so it knows how to send/read transactions)
  const registry = new ethers.Contract(
    CONTRACT_ADDRESSES.Registry,
    RegistryArtifact.abi,
    signerOrProvider
  );

  const job = new ethers.Contract(
    CONTRACT_ADDRESSES.Job,
    JobArtifact.abi,
    signerOrProvider
  );

  const reputation = new ethers.Contract(
    CONTRACT_ADDRESSES.Reputation,
    ReputationArtifact.abi,
    signerOrProvider
  );

  // return them as a single object so callers can grab whichever ones
  // they need with destructuring, e.g. const { job } = getContracts(signer);
  return {
    registry: registry,
    job: job,
    reputation: reputation,
  };
}

// ---------------------------------------------------------------------
// Role constants
// ---------------------------------------------------------------------
// the Registry contract has a Role enum that looks like this in Solidity:
//   enum Role { None, Freelancer, Client, Verifier }
//
// when we get the role back from the chain, it comes through as a number
// (0, 1, 2 or 3) because enums in Solidity are just numbers under the
// hood. so we define matching constants here for readability - it's way
// clearer to write `currentRole === ROLE_FREELANCER` than `currentRole === 1`.
//
// the order has to match the Registry contract exactly. if we ever change
// the enum order over there we have to change it here too. that's a bit
// brittle tbh but it'll do for the assignment.
//
// TODO: figure out if there's a way to auto-generate these from the ABI
// so we don't have to keep them in sync by hand
export const ROLE_NONE = 0;
export const ROLE_FREELANCER = 1;
export const ROLE_CLIENT = 2;
export const ROLE_VERIFIER = 3;

// ---------------------------------------------------------------------
// getRoleLabel
// ---------------------------------------------------------------------
// turns a role number into a human-readable label for the UI. used in
// the header where we say "Role: Freelancer" etc.
//
// we use if/else if instead of a switch because it reads a bit more
// like English. doesn't matter much performance-wise.
// ---------------------------------------------------------------------
export function getRoleLabel(roleNumber) {
  if (roleNumber === ROLE_FREELANCER) {
    return "Freelancer";
  } else if (roleNumber === ROLE_CLIENT) {
    return "Client";
  } else if (roleNumber === ROLE_VERIFIER) {
    return "Verifier";
  } else {
    // covers ROLE_NONE (which means not registered yet) and any garbage
    // values that might come back unexpectedly - safer to treat them all
    // as "not registered" than to display something weird
    return "Not registered";
  }
}

// ---------------------------------------------------------------------
// Status constants
// ---------------------------------------------------------------------
// same idea as the role constants but for the Job contract's Status enum:
//   enum Status { None, Open, Accepted, Completed, Confirmed }
//
// used everywhere we need to render or check what state a job is in.
// ---------------------------------------------------------------------
export const STATUS_NONE = 0;
export const STATUS_OPEN = 1;
export const STATUS_ACCEPTED = 2;
export const STATUS_COMPLETED = 3;
export const STATUS_CONFIRMED = 4;

// ---------------------------------------------------------------------
// getStatusLabel
// ---------------------------------------------------------------------
// turns a status number into a readable label, like "Open" or "Confirmed".
// shown on the job cards in the UI.
// ---------------------------------------------------------------------
export function getStatusLabel(statusNumber) {
  if (statusNumber === STATUS_OPEN) {
    return "Open";
  } else if (statusNumber === STATUS_ACCEPTED) {
    return "Accepted";
  } else if (statusNumber === STATUS_COMPLETED) {
    return "Completed";
  } else if (statusNumber === STATUS_CONFIRMED) {
    return "Confirmed";
  } else {
    // shouldn't really happen but if it does we'd rather show "Unknown"
    // than nothing at all
    return "Unknown";
  }
}